# kubectl create -f to import
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-06-08T14:35:32Z"
  labels:
    app: lvm-ieb
  name: lvm-ieb
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - image: localhost/lvm_actor:latest
    name: lvm-ieb
    imagePullPolicy: Never
    securityContext:
      capabilities: {}
    volumeMounts:
    - mountPath: /root/lvmieb
      name: data-lvm-host-1
    env:
    - name: LVM_ACTOR
      value: "lvmieb"
    - name: LVM_ACTOR_ARGS
      value: "--verbose"
    - name: LVM_DEBUG
      value: "yes"
    - name: LVM_RMQ_HOST
      value: "192.168.49.2"
  volumes:
  - name: data-lvm-host-1
    hostPath:
      path: /lvm/lvmieb
      type: Directory


    
