apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-06-08T14:35:32Z"
  labels:
    app: lvm-sci-agcam-sim
  name: lvm-sci-agcam-sim
spec:
  privileged: true
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - '*'
  volumes:
  - '*'
  hostNetwork: true
  hostPorts:
  - min: 2048
    max: 65535
  hostIPC: true
  hostPID: true
  containers:
  - image: ghcr.io/wasndas/lvmcam:0.0.10
    name: lvm-sci-agcam
    securityContext:
      capabilities: {}
    volumeMounts:
    - mountPath: /root/lvmcam
      name: data-lvm-host-1
    - mountPath: /data
      name: data-lvm-host-2
    env:
    - name: LVMT_CAM
      value: "lvm.sci.agcam"
    - name: LVMT_DEBUG
      value: "true"
    - name: LVMT_CAM_TYPE
      value: "skymakercam"
    - name: LVMT_RMQ
      value: "192.168.49.2"
    - name: LVM_DATA_ROOT
      value: "/data"
  - hostPath:
      path: /lvm/wasndas/lvmcam
      type: Directory
    name: data-lvm-host-1
  - hostPath:
      path: /lvm/var/data
      type: Directory
    name: data-lvm-host-2

