# kubectl create -f to import
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-06-08T14:35:32Z"
  labels:
    app: lvm-scp
  name: lvm-scp
spec:
  terminationGracePeriodSeconds: 3
  containers:
  - image: localhost/lvm_actor:latest
    name: lvm-scp
    imagePullPolicy: Never
    securityContext:
      capabilities: {}
    volumeMounts:
    - mountPath: /root/lvmscp
      name: data-lvm-host-1
    - mountPath: /data
      name: data-lvm-host-2
    env:
    - name: LVM_ACTOR
      value: "lvmscp"
    - name: LVM_DEBUG
      value: "yes"
    - name: LVM_RMQ_HOST
      value: "192.168.49.2"
  volumes:
  - name: data-lvm-host-1
    hostPath:
      path: /lvm/lvmscp
      type: Directory
  - hostPath:
      path: /lvm/var/data
      type: Directory
    name: data-lvm-host-2



    
