apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-06-08T14:35:32Z"
  labels:
    app: lvm-scraper
  name: lvm-scraper
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - image: localhost/lvm_actor:latest
    name: lvm-scraper
    ports:
    - containerPort: 8085
      hostPort: 8085
    securityContext:
      capabilities: {}
    volumeMounts:
    - mountPath: /root/lvm
      name: data-lvm-host-1
    env:
    - name: LVM_ACTOR
      value: "lvmscraper"
    - name: LVM_ACTOR_CONFIG
      value: "scraper"
    - name: LVM_ACTOR_ARGS
      value: "--verbose"
    - name: LVM_DEBUG
      value: "yes"
    - name: LVM_RMQ_HOST
      value: "192.168.49.2"
  volumes:
  - hostPath:
      path: /lvm
      type: Directory
    name: data-lvm-host-1

